name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 8 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header
          config_timezone: Australia/Perth
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          config_order: base.header, isocalendar, languages, traffic, wakatime
          token: ${{ secrets.METRICS_TOKEN }}
